DROP DATABASE IF EXISTS DW;
CREATE DATABASE DW;

CREATE SCHEMA clean;
CREATE SCHEMA final;
CREATE SCHEMA load;
CREATE SCHEMA master;
CREATE SCHEMA normalize;
CREATE SCHEMA normalized;
CREATE SCHEMA raw_source;
CREATE SCHEMA review;
CREATE SCHEMA staging;
CREATE SCHEMA validation;
